import moment from 'moment';

// Hardcode days for the sake of simplicity
const days = [ 'Today', 'Tomorrow', moment().add(2, 'days').format('ddd, MMM D') ];
// Same for times
const times = [ '9:00 AM', '11:10 AM', '12:00 PM', '1:50 PM', '4:30 PM', '6:00 PM', '7:10 PM', '9:45 PM' ];

export const parks = [
  {
    name: 'Park A',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg?auto=format',
    owner: 'Gaston',
    total_places : 50,
    empty_places: 20,
    days,
    times,
  },
  {
    name: 'Park B',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg?auto=format',
    owner: 'Dali',
    total_places : 50,
    empty_places: 28,
    days,
    times,
  },
  {
    name: 'Park C',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg?auto=format',
    owner: 'Dhia',
    total_places : 50,
    empty_places: 12,
    days,
    times,
  },
  {
    name: 'Park D',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg?auto=format',
    owner: 'Houda',
    total_places : 50,
    empty_places: 24,
    days,
    times,
  },
  {
    name: 'Park E',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg?auto=format',
    owner: 'Ali',
    total_places : 50,
    empty_places: 17,
    days,
    times,
  },
  {
    name: 'Park F',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg?auto=format',
    owner: 'Ilyes',
    total_places : 50,
    empty_places: 24,
    days,
    times,
  },
  {
    name: 'Park G',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg?auto=format',
    owner: 'Wajdi',
    total_places : 50,
    empty_places: 12,
    days,
    times,
  },
  {
    name: 'Park H',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg?auto=format',
    owner: 'Nouha',
    total_places : 50,
    empty_places: 6,
    days,
    times,
  },
  {
    name: 'Park F',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg?auto=format',
    owner: 'Hassine',
    total_places : 50,
    empty_places: 34,
    days,
    times,
  },
  {
    name: 'Park I',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg?auto=format',
    owner: 'Nadhem',
    total_places : 50,
    empty_places: 11,
    days,
    times,
  },
  {
    name: 'Park J',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg?auto=format',
    owner: 'Myriam',
    total_places : 50,
    empty_places: 18,
    days,
    times,
  },
  {
    name: 'Park K',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg?auto=format',
    owner: 'Achref',
    total_places : 50,
    empty_places: 23,
    days,
    times,
  },
]