import moment from 'moment';

// Hardcode days for the sake of simplicity
const days = [ 'Today', 'Tomorrow', moment().add(2, 'days').format('ddd, MMM D') ];
// Same for times
const times = [ '9:00 AM', '11:10 AM', '12:00 PM', '1:50 PM', '4:30 PM', '6:00 PM', '7:10 PM', '9:45 PM' ];

export const movies = [
  {
    title: 'Park A',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg',
    owner: 'Gaston',
    total_places : 50,
    genre: 20,
    days,
    times,
  },
  {
    title: 'Park B',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg',
    owner: 'Dali',
    total_places : 50,
    genre: 28,
    days,
    times,
  },
  {
    title: 'Park C',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg',
    owner: 'Dhia',
    total_places : 50,
    genre: 12,
    days,
    times,
  },
  {
    title: 'Park D',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg',
    owner: 'Houda',
    total_places : 50,
    genre: 24,
    days,
    times,
  },
  {
    title: 'Park E',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg',
    owner: 'Ali',
    total_places : 50,
    genre: 17,
    days,
    times,
  },
  {
    title: 'Park F',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg',
    owner: 'Ilyes',
    total_places : 50,
    genre: 24,
    days,
    times,
  },
  {
    title: 'Park G',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg',
    owner: 'Wajdi',
    total_places : 50,
    genre: 12,
    days,
    times,
  },
  {
    title: 'Park H',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg',
    owner: 'Nouha',
    total_places : 50,
    genre: 6,
    days,
    times,
  },
  {
    title: 'Park F',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg',
    owner: 'Hassine',
    total_places : 50,
    genre: 34,
    days,
    times,
  },
  {
    title: 'Park I',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg',
    owner: 'Nadhem',
    total_places : 50,
    genre: 11,
    days,
    times,
  },
  {
    title: 'Park J',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg',
    owner: 'Myriam',
    total_places : 50,
    genre: 18,
    days,
    times,
  },
  {
    title: 'Park K',
    poster : 'https://www.datocms-assets.com/17742/1575299320-parking-1-4.jpg',
    owner: 'Achref',
    total_places : 50,
    genre: 23,
    days,
    times,
  },
]
// import moment from 'moment';

// // Hardcode days for the sake of simplicity
// const days = [ 'Today', 'Tomorrow', moment().add(2, 'days').format('ddd, MMM D') ];
// // Same for times
// const times = [ '9:00 AM', '11:10 AM', '12:00 PM', '1:50 PM', '4:30 PM', '6:00 PM', '7:10 PM', '9:45 PM' ];

// export const movies = [
//   {
//     title: 'La La Land',
//     poster: 'https://i.imgur.com/po7UezG.jpg',
//     genre: 'Drama/Romance',
//     days,
//     times,
//   },
//   {
//     title: 'Paterson',
//     poster: 'https://i.imgur.com/pE0C9E0.jpg',
//     genre: 'Drama/Comedy',
//     days,
//     times,
//   },
//   {
//     title: 'Jackie',
//     poster: 'https://i.imgur.com/VqUi1sw.jpg',
//     genre: 'Drama/Biography',
//     days,
//     times,
//   },
//   {
//     title: 'Lo and Behold Reveries of the Connected World',
//     poster: 'https://i.imgur.com/s106X7S.jpg',
//     genre: 'Documentary',
//     days,
//     times,
//   },
//   {
//     title: '10 Cloverfield Lane',
//     poster: 'https://i.imgur.com/kV2BVdH.jpg',
//     genre: 'Drama',
//     days,
//     times,
//   },
//   {
//     title: 'Birth of a Nation',
//     poster: 'https://i.imgur.com/a6HJj8S.jpg',
//     genre: 'Fantasy/Myster',
//     days,
//     times,
//   },
//   {
//     title: 'De Palma',
//     poster: 'https://i.imgur.com/oOIa73M.jpg',
//     genre: 'Documentary',
//     days,
//     times,
//   },
//   {
//     title: 'Doctor Strange',
//     poster: 'https://i.imgur.com/kyHDVOk.jpg',
//     genre: 'Fantasy/Science Fiction',
//     days,
//     times,
//   },
//   {
//     title: 'Eddie the Eagle',
//     poster: 'https://i.imgur.com/GNrdAuF.jpg',
//     genre: 'Drama/Sport',
//     days,
//     times,
//   },
//   {
//     title: 'Pride and prejudice and zombies',
//     poster: 'https://i.imgur.com/KhbG0Lw.jpg',
//     genre: 'Thriller/Action',
//     days,
//     times,
//   },
//   {
//     title: 'Finding Dory',
//     poster: 'https://i.imgur.com/BTexHYJ.jpg',
//     genre: 'Comedy/Adventure',
//     days,
//     times,
//   },
//   {
//     title: 'Green Room',
//     poster: 'https://i.imgur.com/Q0Ysh7L.jpg',
//     genre: 'Crime/Thriller',
//     days,
//     times,
//   },
//   {
//     title: 'Kubo and the Two Strings',
//     poster: 'https://i.imgur.com/uTFCKZc.jpg',
//     genre: 'Fantasy/Adventure',
//     days,
//     times,
//   },
//   {
//     title: 'In a Valley of Violence',
//     poster: 'https://i.imgur.com/DTtJ62G.jpg',
//     genre: 'Drama/Western',
//     days,
//     times,
//   },
//   {
//     title: 'O.J.: Made in America',
//     poster: 'https://i.imgur.com/T8uc6x8.jpg',
//     genre: 'Documentary',
//     days,
//     times,
//   },
//   {
//     title: 'Rogue One: A Star Wars Story',
//     poster: 'https://i.imgur.com/zOF2iYc.jpg',
//     genre: 'Science Fiction/Action',
//     days,
//     times,
//   },
//   {
//     title: 'Sing Street',
//     poster: 'https://i.imgur.com/C3ExEb6.jpg',
//     genre: 'Drama/Romance',
//     days,
//     times,
//   },
//   {
//     title: 'Zoolander 2',
//     poster: 'https://i.imgur.com/ejlIijD.jpg',
//     genre: 'Comedy',
//     days,
//     times,
//   },
// ];